#!/bin/bash

set -e

sudo apt-get install emacs24-nox curl tree unzip zip

cd $(dirname $0)

cp .emacs ~
cp .bashrc ~
cp .gemrc ~
cp .gitconfig ~
cp .profile ~
cp .tmux.conf ~

sudo cp hub /usr/local/bin
