#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1

sudo apt-get install -y emacs24-nox curl tree unzip zip mosh

cd $(dirname $0)

cp .emacs ~
cp .bashrc ~
cp .gemrc ~
cp .gitconfig ~
cp .profile ~
cp .tmux.conf ~

sudo cp hub /usr/local/bin

sudo wget -qO /usr/local/bin/lein https://raw.github.com/technomancy/leiningen/stable/bin/lein
